# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Final(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 843)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setGeometry(QRect(11, 11, 1092, 796))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(56, 58, 89);\n"
"color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_title = QLabel(self.frame)
        self.label_title.setGeometry(QRect(0, 0, 1091, 71))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(Qt.LeftToRight)
        self.label_title.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_title.setTextFormat(Qt.AutoText)
        self.label_title.setAlignment(Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_title_2 = QLabel(self.frame)
        self.label_title_2.setGeometry(QRect(0, 90, 861, 71))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_title_2.setFont(font)
        self.label_title_2.setLayoutDirection(Qt.LeftToRight)
        self.label_title_2.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_title_2.setTextFormat(Qt.AutoText)
        self.label_title_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_title_2.setObjectName("label_title_2")
        self.run_button = QPushButton(self.frame)
        self.run_button.setGeometry(QRect(270, 600, 291, 111))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.run_button.setFont(font)
        self.run_button.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(10, 242, 251, 255), stop:1 rgba(224, 6, 159, 255));\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(20, 252, 255, 255), stop:1 rgba(234, 26, 179, 255));\n"
"    border-radius: 30px;\n"
"border-left: 1px solid rgb(37, 1, 59);\n"
"border-right: 2px solid rgb(37, 1, 59);\n"
"border-bottom: 3px solid rgb(37, 1, 59);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(0, 232, 235, 255), stop:1 rgba(214, 6, 149, 255));\n"
"border-radius: 30px;\n"
"border-left: 2px solid rgb(37, 1, 59);\n"
"border-right: 1px solid rgb(37, 1, 59);\n"
"border-top: 3px solid rgb(37, 1, 59);\n"
"border-bottom: none;\n"
"}")
        self.run_button.setObjectName("run_button")


        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QRect(10, 160, 841, 101))
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QWidget(self.groupBox_2)
        self.widget.setGeometry(QRect(21, 31, 821, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ratio = QCheckBox(self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratio.sizePolicy().hasHeightForWidth())
        self.ratio.setSizePolicy(sizePolicy)
        self.ratio.setMinimumSize(QSize(200, 30))
        font = QFont()
        font.setFamily("a타이틀고딕1")
        font.setPointSize(15)
        self.ratio.setFont(font)
        self.ratio.setStyleSheet("color: rgb(224, 211, 255);")
        self.ratio.setObjectName("ratio")
        self.horizontalLayout.addWidget(self.ratio)
        self.num_ratio = QCheckBox(self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_ratio.sizePolicy().hasHeightForWidth())
        self.num_ratio.setSizePolicy(sizePolicy)
        self.num_ratio.setMinimumSize(QSize(200, 30))
        font = QFont()
        font.setFamily("a타이틀고딕1")
        font.setPointSize(15)
        self.num_ratio.setFont(font)
        self.num_ratio.setStyleSheet("color: rgb(224, 211, 255);")
        self.num_ratio.setObjectName("num_ratio")
        self.horizontalLayout.addWidget(self.num_ratio)
        self.sexRatio = QCheckBox(self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sexRatio.sizePolicy().hasHeightForWidth())
        self.sexRatio.setSizePolicy(sizePolicy)
        self.sexRatio.setMinimumSize(QSize(200, 30))
        font = QFont()
        font.setFamily("a타이틀고딕1")
        font.setPointSize(15)
        self.sexRatio.setFont(font)
        self.sexRatio.setStyleSheet("color: rgb(224, 211, 255);")
        self.sexRatio.setObjectName("sexRatio")
        self.horizontalLayout.addWidget(self.sexRatio)

        self.ratio.stateChanged.connect(self.favorite)
        self.num_ratio.stateChanged.connect(self.favorite)
        self.sexRatio.stateChanged.connect(self.favorite)


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)


    def favorite(self):
        if self.ratio.isChecked():
             print("평점 체크")
        if self.num_ratio.isChecked():
            print("평점수 체크")
        if self.sexRatio.isChecked():
            print("성비 체크")


    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<strong>Animation recommender"))
        self.label_title_2.setText(_translate("MainWindow", "    4. 중요하게 생각하는 요소는 무었인가요?"))
        self.run_button.setText(_translate("MainWindow", "RUN"))
        self.ratio.setText(_translate("MainWindow", "평점"))
        self.num_ratio.setText(_translate("MainWindow", "평점수"))
        self.sexRatio.setText(_translate("MainWindow", "성비"))

